name: League Ranker Build Checks
on:
  push:
  pull_request:
    types:
      - opened
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
      - name: Run linting checks
        run: |
          make check
      - name: Test with pytest
        run: |
          pytest
